### ISSUE TITLE
Questions about Text Feature Extraction and Enhancement in Counting Task Performance

### ISSUE THREAD

**Issue by Hadlay-Zhang** [Cyanogenoid/vqa-counting#13]
Hi. Thanks for your code sharing. I'm currently experimenting on your counting model.

During my experiments with varying configurations when I attempted to substitute the GRU-based text feature extraction model with more sophisticated architectures (i.e., Transformer-based ones), there was no noticeable improvement in counting task accuracy.

Does it mean that for counting tasks, the focus should be more on fusion and attention mechanisms rather than improving modal feature extraction approach?

**Comment by Cyanogenoid** [comment]
Given your results, I would guess so. Perhaps it's because the questions tend to be fairly simple in terms of understanding them (so the current language model is sufficient), so the challenge is more in terms of relating the question to the image accurately. Better image features should help as well I would think.

**Comment by Hadlay-Zhang** [comment]
Great! Thanks a lot :)
